### ISSUE TITLE
How to perform the "pen mark" removal  and color normalization 

### ISSUE THREAD

**Issue by archanabhardwaj** [smujiang/WSITools#6]
Hello 
I found your method very useful. I am interested to apply WSItools for WSI image data analysis and prepare data ready for the deep learning. I have multiple "svs" format slide images. Some of these WSI, consists of "pen" marks.  I am planning to follow analysis as  :
 remove "pen" marks -> apply color normalization -> tissue detection and patches extraction.
From this method, tissue detection and patches extraction works perfectly fine. How can I tackle the issue of "pen mark" removal and "color normalization" in my datasets. I would appreciate all the suggestions. 

Thanks in advance

**Comment by smujiang** [comment]
Glad to hear this tool is useful to you.
Please refer to my [another repo](https://github.com/smujiang/WSIPenMarkingRemoval) for pen marking removal. Generally, I agree with your workflow. But there will be slight differences if you would like to use our model. First, the pen marking removal model takes all the foreground (no matter pen-marking, tissue, or tissue covered by pen-marking) as input (You can, but you don't need to classify different image content); Second, our pen-marking removal model actually do the normalization at the same time of removing pen-marks, as the model is trained on a pairwise manner on a large dataset with the same scanner settings. Please refer to our paper for more details. Third, after pen-marking removal, you can just discard the image patches without tissue, rather than do patch extraction again.
Last suggestion, I would not recommend all these complex steps if you have better data sources. High quality data always helps you to have an easy start if you're focusing on biomedical questions, rather than trivial techniques.

**Comment by archanabhardwaj** [comment]
Thanks alot for your suggestion.
